
export const LOGIN_LOADING = "LOGIN_LOADING";
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const PROFIL_PHOTO_LOADING ="PROFIL_PHOTO_LOADING"
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const UPDATE_CONVERSATION_ACTION = "UPDATE_CONVERSATION_ACTION";
export const UPDATE_CONVERSATION_SEND_INFO = "UPDATE_CONVERSATION_SEND_INFO";
export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_LOADING = "GET_POSTS_LOADING";
export const CREATE_POST = "CREATE_POST"

